### ISSUE TITLE
SyntaxError: Unexpected string line 4

### ISSUE THREAD

**Issue by non7top** [timdp/asdf-bump#1]
Hello, just wanted to try this and faced an issue. Running ubuntu 22.04

```shell
$ asdf-bump --help
/home/hmh/.nvm/versions/node/v12.9.0/lib/node_modules/asdf-bump/dist/asdf-bump.js:4
import "source-map-support/register.js";
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11

$ npm --version
6.10.2
```

**Comment by non7top** [comment]
I might have an outdated node though, not sure...

**Comment by non7top** [comment]
nvm, updated to latest node and seems to be working fine.
